# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('img_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота (px)')),
                ('img_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина (px)')),
                ('photo', models.ImageField(blank=True, height_field='img_height', upload_to='avatars/', verbose_name='Фотография', width_field='img_width')),
                ('website', models.URLField(blank=True, default='', verbose_name='Вебсайт')),
                ('bio', models.TextField(blank=True, default='', verbose_name='О себе')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Страна')),
                ('language', models.CharField(choices=[('ru', 'Russin'), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
