# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0003_auto_20170212_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_height',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img_width',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, height_field=models.PositiveIntegerField(), upload_to='avatars/', width_field=models.PositiveIntegerField()),
        ),
    ]
