# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-12 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0004_auto_20170212_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, height_field='img_height', upload_to='avatars/', width_field='img_width'),
        ),
    ]
