# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0005_auto_20170212_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='ru', max_length=5),
        ),
    ]
