# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0006_auto_20170213_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
