# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 21:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0008_auto_20170213_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='update',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 2, 17, 21, 54, 46, 28076, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
