# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-17 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0009_userprofile_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='update',
            new_name='last_update',
        ),
    ]
