# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('pub_date', models.DateField()),
                ('enable_comments', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Список комментариев',
                'verbose_name': 'Список комментариев',
            },
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Список записей', 'verbose_name_plural': 'Список записей'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Запись в блоге', 'verbose_name_plural': 'Записи в блоге'},
        ),
        migrations.AlterModelOptions(
            name='blogtagindexpage',
            options={'verbose_name': 'Список тегов', 'verbose_name_plural': 'Список тегов'},
        ),
    ]
