# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import meta.models
import modelcluster.fields
import wagtail.wagtailcore.fields
import wagtail_modeltranslation.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('blog', '0002_auto_20170312_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Список записей FAQ',
                'verbose_name_plural': 'Список записей FAQ',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Post date of FAQ')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Запись в FAQ',
                'verbose_name_plural': 'Записи в FAQ',
            },
            bases=(wagtail_modeltranslation.models.TranslationMixin, meta.models.ModelMeta, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='FaqPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('faqpage', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_images', to='blog.FaqPage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=(wagtail_modeltranslation.models.TranslationMixin, models.Model),
        ),
    ]
