# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170316_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='caption_en',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='caption_ru',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
