# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_faqlistpage_faqpage_faqpageimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloglistpage',
            options={'verbose_name': 'Список записей в Блоге', 'verbose_name_plural': 'Список записей в Блоге'},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Запись в Блоге', 'verbose_name_plural': 'Записи в Блоге'},
        ),
        migrations.AddField(
            model_name='faqpage',
            name='body_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='body_ru',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='title_ru',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title'),
        ),
    ]
