# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body_en',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body_ru',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='intro_ru',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
