# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vCard_expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(blank=True, default='', max_length=256, verbose_name='Знание')),
                ('type', models.CharField(choices=[('beginner', 'Начальный'), ('average', 'Средний'), ('expert', 'Эксперт')], default='average', max_length=20, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'vCard Знание',
                'verbose_name_plural': ' vCard Знания',
            },
        ),
        migrations.CreateModel(
            name='vCard_hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(blank=True, default='', max_length=256, verbose_name='Увлечение')),
                ('type', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=20, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'vCard Знание',
                'verbose_name_plural': ' vCard Знания',
            },
        ),
        migrations.CreateModel(
            name='vCard_impp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=256, verbose_name='URL')),
                ('prefer', models.BooleanField(default=False, verbose_name='Предпочтительный')),
            ],
            options={
                'verbose_name': 'vCard социальная сеть',
                'verbose_name_plural': ' vCard социальнае сети',
            },
        ),
        migrations.CreateModel(
            name='vCard_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, default='', max_length=256, verbose_name='Интерес')),
                ('type', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=20, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'vCard Интерес',
                'verbose_name_plural': ' vCard Интересы',
            },
        ),
        migrations.CreateModel(
            name='vCard_organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(blank=True, default='', max_length=100, verbose_name='Правовая форма')),
                ('org', models.CharField(blank=True, default='', max_length=256, verbose_name='Наименование организации')),
                ('any', models.CharField(blank=True, default='', max_length=100, verbose_name='Дополнительно')),
                ('prefer', models.BooleanField(default=False, verbose_name='Предпочтительный')),
            ],
            options={
                'verbose_name': 'vCard Организация',
                'verbose_name_plural': ' vCard Организации',
            },
        ),
        migrations.CreateModel(
            name='vCard_related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('contact', 'Контактируем'), ('acquaintance', 'Знакомый/Знакомая'), ('friend', 'Друг/Подружка'), ('met', 'Встречились'), ('co-worker', 'Сотрудник/Сотрудница'), ('colleague', 'Коллега'), ('co-resident', 'Живем вместе'), ('neighbor', 'Сосед'), ('child', 'Ребенок'), ('parent', 'Родитель'), ('sibling', 'Брат/Сестра'), ('spouse', 'Супруг(а)'), ('kin', 'Родственник'), ('muse', 'Муза'), ('crush', 'Подавляет'), ('date', 'Встречаемся'), ('sweetheart', 'Любимый/Любимая'), ('me', 'Я сам'), ('agent', 'Доверенное лицо'), ('emergency', 'Запасной')], default='contact', max_length=20, verbose_name='Тип связи')),
                ('king', models.CharField(choices=[('individual', 'Индивидульная'), ('organization', 'Организация'), ('group', 'Группа'), ('location', 'Местонахождение')], default='group', max_length=20, verbose_name='Тип связи')),
            ],
            options={
                'verbose_name': 'vCard Связь',
                'verbose_name_plural': ' vCard Связи',
            },
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='fn',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='n',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='org',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='role',
        ),
        migrations.RemoveField(
            model_name='vcard',
            name='title',
        ),
        migrations.AddField(
            model_name='vcard',
            name='main_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard_names', verbose_name='Владелец vCard'),
        ),
        migrations.AddField(
            model_name='vcard_adress',
            name='prefer',
            field=models.BooleanField(default=False, verbose_name='Предпочтительный'),
        ),
        migrations.AddField(
            model_name='vcard_email',
            name='prefer',
            field=models.BooleanField(default=False, verbose_name='Предпочтительный'),
        ),
        migrations.AddField(
            model_name='vcard_email',
            name='type',
            field=models.CharField(choices=[('home', 'Домашний'), ('work', 'Рабочий')], default='home', max_length=20, verbose_name='Тип email'),
        ),
        migrations.AddField(
            model_name='vcard_names',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ник'),
        ),
        migrations.AddField(
            model_name='vcard_names',
            name='role',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='vcard_names',
            name='sort_as',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='vcard_names',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='vcard_phone',
            name='prefer',
            field=models.BooleanField(default=False, verbose_name='Предпочтительный'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='model_version',
            field=models.CharField(default='4.0', max_length=7, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='vcard_related',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='vcard_related',
            name='relate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_relate', to='informer_vcard.vCard'),
        ),
        migrations.AddField(
            model_name='vcard_organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='vcard_interest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='vcard_impp',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='vcard_hobby',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='vcard_expertise',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard', verbose_name='Владелец'),
        ),
    ]
