# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard',
            name='bday',
        ),
        migrations.AddField(
            model_name='vcard_names',
            name='bday',
            field=models.DateTimeField(blank=True, help_text='День рождения или создания', null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='sound',
            field=models.FileField(blank=True, help_text='Голос или музыкальное сопровождение mp3, ogg, wav', upload_to='vcard_sound/', verbose_name='Звук'),
        ),
    ]
