# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0002_auto_20170511_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcard_adress',
            old_name='adr',
            new_name='adress',
        ),
        migrations.AlterField(
            model_name='vcard_phone',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Рекомендуется как основной', verbose_name='Предпочтительный'),
        ),
        migrations.AlterField(
            model_name='vcard_phone',
            name='type',
            field=models.CharField(choices=[('home', 'По месту проживания'), ('work', 'По месту работы'), ('voice', 'Для голосового общения'), ('fax', 'Для передачи факсов'), ('cell', 'Сотовый'), ('pager', 'Для передачи сообщений на пейджер'), ('bbs', 'Обслуживает электронную доску объявлений'), ('car', 'Автомобильный')], default='cell', help_text='Тип телефона', max_length=20, verbose_name='Тип телефона'),
        ),
    ]
