# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0002_auto_20170331_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcard_adress',
            options={'verbose_name': 'vCard Адрес', 'verbose_name_plural': ' vCard Адреса'},
        ),
        migrations.AlterModelOptions(
            name='vcard_category',
            options={'verbose_name': 'vCard Категория', 'verbose_name_plural': ' vCard Категории'},
        ),
        migrations.AlterModelOptions(
            name='vcard_email',
            options={'verbose_name': 'vCard Email', 'verbose_name_plural': ' vCard Email'},
        ),
        migrations.AlterModelOptions(
            name='vcard_hobby',
            options={'verbose_name': 'vCard Увлечение', 'verbose_name_plural': ' vCard Увлечения'},
        ),
        migrations.AlterModelOptions(
            name='vcard_impp',
            options={'verbose_name': 'vCard Социальная сеть', 'verbose_name_plural': ' vCard Социальнае сети'},
        ),
        migrations.AlterModelOptions(
            name='vcard_names',
            options={'verbose_name': 'vCard Имена', 'verbose_name_plural': ' vCard Имена'},
        ),
        migrations.AlterModelOptions(
            name='vcard_phone',
            options={'verbose_name': 'vCard Телефон', 'verbose_name_plural': ' vCard Телефоны'},
        ),
        migrations.AlterField(
            model_name='vcard',
            name='bday',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='main_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard_names', verbose_name='Владелец vCard'),
        ),
        migrations.AlterField(
            model_name='vcard_related',
            name='king',
            field=models.CharField(choices=[('individual', 'Индивидульная'), ('organization', 'Организация'), ('group', 'Группа'), ('location', 'Местонахождение')], default='group', max_length=20, verbose_name='Вид группы'),
        ),
    ]
