# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0003_auto_20170402_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard_names',
            name='full_name',
            field=models.CharField(default='', max_length=256, verbose_name='Полное имя'),
        ),
    ]
