# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0004_auto_20170519_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard_category',
            name='owner',
        ),
        migrations.AddField(
            model_name='vcard',
            name='category',
            field=models.CharField(default='', help_text='Категория информации', max_length=256, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='label',
            field=models.CharField(blank=True, default='', help_text='Основное представление', max_length=256, verbose_name='Представление'),
        ),
        migrations.AlterField(
            model_name='vcard_adress',
            name='adress',
            field=models.CharField(blank=True, default='', help_text='Полный адрес строкой', max_length=256, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vcard_email',
            name='type',
            field=models.CharField(choices=[('home', 'Домашний'), ('work', 'Рабочий')], default='home', help_text='Тип электронного почтового адреса', max_length=20, verbose_name='Тип email'),
        ),
        migrations.AlterField(
            model_name='vcard_phone',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Телефон с кодом города', max_length=128, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='vCard_category',
        ),
    ]
