# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0004_auto_20170404_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard_adress',
            name='adr',
            field=models.CharField(default='', max_length=256, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='vcard_category',
            name='category',
            field=models.CharField(default='', max_length=256, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='vcard_expertise',
            name='expertise',
            field=models.CharField(default='', max_length=256, verbose_name='Знание'),
        ),
        migrations.AlterField(
            model_name='vcard_hobby',
            name='expertise',
            field=models.CharField(default='', max_length=256, verbose_name='Увлечение'),
        ),
        migrations.AlterField(
            model_name='vcard_impp',
            name='url',
            field=models.URLField(max_length=256, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='vcard_interest',
            name='interest',
            field=models.CharField(default='', max_length=256, verbose_name='Интерес'),
        ),
        migrations.AlterField(
            model_name='vcard_organization',
            name='org',
            field=models.CharField(default='', max_length=256, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='vcard_phone',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vcard_related',
            name='relate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_relate', to='informer_vcard.vCard'),
        ),
    ]
