# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0005_auto_20170521_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vCard_impp',
            new_name='vCard_social',
        ),
    ]
