# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields
import ool


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0006_auto_20170404_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='bday',
            field=models.DateTimeField(blank=True, help_text='День рождения (создания)', verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='revision',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='secure_class',
            field=models.CharField(choices=[('public', 'публично'), ('private', 'приватно'), ('confidential', 'конфедициально')], default='public', help_text='Уровень доступа к этой информации', max_length=20, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='sound',
            field=models.FileField(blank=True, help_text='Звуковой файл', upload_to='vcard_media/', verbose_name='Звуковой файл'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='draft', help_text='Статус объекта', max_length=100, no_check_for_status=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='version',
            field=ool.VersionField(default=0, verbose_name='Версия Object Optimistic Lock'),
        ),
        migrations.AlterField(
            model_name='vcard_email',
            name='type',
            field=models.CharField(choices=[('home', 'домашний'), ('work', 'рабочий')], default='home', help_text='Тип электронного почтового адреса', max_length=20, verbose_name='Тип email'),
        ),
        migrations.AlterField(
            model_name='vcard_organization',
            name='form',
            field=models.CharField(blank=True, default='', help_text='Организационно правовая форма предприятия', max_length=100, verbose_name='Правовая форма'),
        ),
    ]
