# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0006_auto_20170521_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='vCard_messengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('icq', 'ICQ'), ('skype', 'Skype'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('jabber', 'Jabber'), ('agent', 'Mail.ru Agent'), ('yahoo', 'Yahoo'), ('allo', 'Allo'), ('snapchat', 'Snapchat ')], help_text='Название программы мессанджера', max_length=20, verbose_name='Вид мессанджера')),
                ('identifier', models.TextField(help_text='Логин или идентификатор службы сообщений', max_length=256, verbose_name='Идентификатор')),
                ('prefer', models.BooleanField(default=False, help_text='Рекомендуется как основной', verbose_name='Предпочтительный')),
            ],
            options={
                'verbose_name_plural': 'Мессенджеры',
                'verbose_name': 'Мессенджер',
            },
        ),
        migrations.AlterModelOptions(
            name='vcard',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='vcard_adress',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='vcard_email',
            options={'verbose_name': 'Почта', 'verbose_name_plural': 'Почта'},
        ),
        migrations.AlterModelOptions(
            name='vcard_expertise',
            options={'verbose_name': 'Знание', 'verbose_name_plural': 'Знания'},
        ),
        migrations.AlterModelOptions(
            name='vcard_hobby',
            options={'verbose_name': 'Увлечение', 'verbose_name_plural': 'Увлечения'},
        ),
        migrations.AlterModelOptions(
            name='vcard_interest',
            options={'verbose_name': 'Интерес', 'verbose_name_plural': 'Интересы'},
        ),
        migrations.AlterModelOptions(
            name='vcard_names',
            options={'verbose_name': 'Имена', 'verbose_name_plural': 'Имена'},
        ),
        migrations.AlterModelOptions(
            name='vcard_organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='vcard_phone',
            options={'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='vcard_related',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='vcard_social',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальнае сети'},
        ),
        migrations.AddField(
            model_name='vcard_social',
            name='description',
            field=models.TextField(blank=True, help_text='Логин или идентификатор службы сообщений', max_length=256, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='vcard_messengers',
            name='owner',
            field=models.ForeignKey(help_text='*', on_delete=django.db.models.deletion.CASCADE, to='informer_vcard.vCard', verbose_name='Владелец'),
        ),
    ]
