# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0007_auto_20170410_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard_hobby',
            name='hobby',
            field=models.CharField(default='', help_text='Наименование Увлечения', max_length=256, verbose_name='Увлечение'),
        ),
    ]
