# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0008_vcard_hobby_hobby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcard',
            old_name='secure_class',
            new_name='secure',
        ),
    ]
