# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0009_auto_20170522_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard_adress',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация', max_length=256, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vcard_email',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация', max_length=256, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vcard_phone',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация', max_length=256, verbose_name='Описание'),
        ),
    ]
