# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0010_remove_vcard_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='secure',
            field=models.CharField(choices=[('Public', 'Публично'), ('Private', 'Приватно'), ('Confidential', 'Конфедициально')], default='Public', help_text='Уровень доступа к этой информации', max_length=20, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
    ]
