# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0010_auto_20170522_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard_names',
            name='role',
        ),
        migrations.RemoveField(
            model_name='vcard_names',
            name='title',
        ),
        migrations.AddField(
            model_name='vcard_messengers',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация', max_length=256, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vcard_organization',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Ведущая роль на предприятии', max_length=256, verbose_name='Роль'),
        ),
        migrations.AddField(
            model_name='vcard_organization',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Должность на предприятии', max_length=256, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='vcard_organization',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Основное место работы', verbose_name='Основное'),
        ),
    ]
