# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0011_auto_20170429_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='secure',
            field=models.CharField(choices=[('public', 'Публично'), ('private', 'Приватно'), ('confidential', 'Конфедициально')], default='public', help_text='Уровень доступа к этой информации', max_length=20, verbose_name='Доступ'),
        ),
    ]
