# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0011_auto_20170522_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard_hobby',
            name='expertise',
        ),
        migrations.AddField(
            model_name='vcard_expertise',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Является основным увлечением', verbose_name='Основное увлечние'),
        ),
        migrations.AlterField(
            model_name='vcard_hobby',
            name='hobby',
            field=models.CharField(default='', help_text='Наименование увлечения', max_length=256, verbose_name='Увлечение'),
        ),
    ]
