# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0012_auto_20170522_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard_expertise',
            name='prefer',
        ),
        migrations.AddField(
            model_name='vcard_hobby',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Является основным увлечением', verbose_name='Основное увлечние'),
        ),
    ]
