# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0012_auto_20170429_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
    ]
