# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import ool


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0013_vcard_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='system',
            field=models.CharField(blank=True, default='INFORMERS 0.1', max_length=100, verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='vcard',
            name='version',
            field=ool.VersionField(default=0, verbose_name='OOL'),
        ),
    ]
