# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0013_auto_20170522_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcard_phone',
            name='function',
        ),
        migrations.AddField(
            model_name='vcard_phone',
            name='extension',
            field=models.CharField(default='', help_text='Добавочный номер телефона', max_length=20, verbose_name='Добавочный'),
        ),
        migrations.AlterField(
            model_name='vcard_phone',
            name='type',
            field=models.CharField(choices=[('home', 'По месту проживания'), ('work', 'По месту работы'), ('voice', 'Для голосового общения'), ('fax', 'Для передачи факсов'), ('cell', 'Сотовый'), ('car', 'Автомобильный')], default='cell', help_text='Тип телефона', max_length=20, verbose_name='Тип телефона'),
        ),
        migrations.AlterField(
            model_name='vcard_related',
            name='king',
            field=models.CharField(choices=[('individual', 'Индивидульная'), ('organization', 'Организация'), ('group', 'Группа'), ('location', 'Местонахождение')], default='group', help_text='Вид группы', max_length=20, verbose_name='Вид связи'),
        ),
        migrations.AlterField(
            model_name='vcard_related',
            name='relate',
            field=models.ForeignKey(help_text='Связи с другой информацией', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_relate', to='informer_vcard.vCard', verbose_name='Объект связи'),
        ),
    ]
