# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0014_auto_20170523_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcard_expertise',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Является основным знанием', verbose_name='Основное знание'),
        ),
        migrations.AddField(
            model_name='vcard_interest',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Является основным интересом', verbose_name='Основной интерес'),
        ),
    ]
