# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informer_vcard', '0015_auto_20170528_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcard_adress',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Рекомендуется как основной', verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='vcard_email',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Рекомендуется как основной', verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='vcard_email',
            name='type',
            field=models.CharField(choices=[('home', 'Домашний'), ('work', 'Рабочий'), ('service', 'Сервис')], default='home', help_text='Тип электронного почтового адреса', max_length=20, verbose_name='Тип email'),
        ),
        migrations.AlterField(
            model_name='vcard_messengers',
            name='identifier',
            field=models.CharField(help_text='Логин или идентификатор службы сообщений', max_length=256, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='vcard_messengers',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Рекомендуется как основной', verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='vcard_phone',
            name='extension',
            field=models.CharField(blank=True, default='', help_text='Добавочный номер телефона', max_length=20, verbose_name='Добавочный'),
        ),
        migrations.AlterField(
            model_name='vcard_phone',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Рекомендуется как основной', verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='vcard_phone',
            name='type',
            field=models.CharField(choices=[('home', 'По месту проживания'), ('work', 'По месту работы'), ('fax', 'Для передачи факсов'), ('cell', 'Сотовый мобильный'), ('car', 'Автомобильный')], default='cell', help_text='Тип телефона', max_length=20, verbose_name='Тип телефона'),
        ),
        migrations.AlterField(
            model_name='vcard_social',
            name='prefer',
            field=models.BooleanField(default=False, help_text='Рекомендуется как основной', verbose_name='Основной'),
        ),
    ]
