# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListedDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('domain',),
            },
        ),
        migrations.CreateModel(
            name='XtdComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_comments.Comment')),
                ('thread_id', models.IntegerField(db_index=True, default=0)),
                ('parent_id', models.IntegerField(default=0)),
                ('level', models.SmallIntegerField(default=0)),
                ('order', models.IntegerField(db_index=True, default=1)),
                ('followup', models.BooleanField(default=False, help_text='Receive by email further comments in this conversation')),
            ],
            options={
                'permissions': [('can_moderate', 'Can moderate comments')],
                'ordering': ('submit_date',),
                'abstract': False,
                'verbose_name_plural': 'comments',
                'verbose_name': 'comment',
            },
            bases=('django_comments.comment',),
        ),
    ]
