# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('django_comments_xtd', '0002_commentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='xtdcomment_ptr',
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
